### ISSUE TITLE
Update available in the updates page

### ISSUE THREAD

**Issue by roykho** [nielslange/smntcs-show-symlinked-plugins#3]
There is still a location where the plugin can be updated.

https://capture.dropbox.com/T9n7sGo0UFSrFRpW

Perhaps see if there is a way (hook) to remove symlinked plugins from showing up in this update list page.

**Comment by nielslange** [comment]
Thanks for reporting this, @roykho. I also noticed this. I'm uncertain if there's a hook for this use case, as it's rather specific, but I'll look into it when I have time.

**Comment by roykho** [comment]
So I took a look at this and apparently there are no available hooks in core to facilitate what we want. It's possible to just use JS to manipulate that page but it would be pretty messy because there are too many different components on the page to account for and thus not sure it's worth the effort.

**Comment by nielslange** [comment]
> So I took a look at this and apparently there are no available hooks in core to facilitate what we want. It's possible to just use JS to manipulate that page but it would be pretty messy because there are too many different components on the page to account for and thus not sure it's worth the effort.

I feel like it's not worth the effort in this case. Are you fine with closing this issue, @roykho?
